// Code generated by MockGen. DO NOT EDIT.
// Source: services/wireguard_tunnels.go

// Package services_test is a generated GoMock package.
package services_test

import (
	reflect "reflect"
	models "tunnel-provisioner-service/models"

	gomock "github.com/golang/mock/gomock"
)

// MockWireguardTunnelService is a mock of WireguardTunnelService interface.
type MockWireguardTunnelService struct {
	ctrl     *gomock.Controller
	recorder *MockWireguardTunnelServiceMockRecorder
}

// MockWireguardTunnelServiceMockRecorder is the mock recorder for MockWireguardTunnelService.
type MockWireguardTunnelServiceMockRecorder struct {
	mock *MockWireguardTunnelService
}

// NewMockWireguardTunnelService creates a new mock instance.
func NewMockWireguardTunnelService(ctrl *gomock.Controller) *MockWireguardTunnelService {
	mock := &MockWireguardTunnelService{ctrl: ctrl}
	mock.recorder = &MockWireguardTunnelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWireguardTunnelService) EXPECT() *MockWireguardTunnelServiceMockRecorder {
	return m.recorder
}

// GetProfileInfo mocks base method.
func (m *MockWireguardTunnelService) GetProfileInfo(tunnelId, profileId string) (models.WireguardTunnelProfileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileInfo", tunnelId, profileId)
	ret0, _ := ret[0].(models.WireguardTunnelProfileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileInfo indicates an expected call of GetProfileInfo.
func (mr *MockWireguardTunnelServiceMockRecorder) GetProfileInfo(tunnelId, profileId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileInfo", reflect.TypeOf((*MockWireguardTunnelService)(nil).GetProfileInfo), tunnelId, profileId)
}

// GetTunnelConfigById mocks base method.
func (m *MockWireguardTunnelService) GetTunnelConfigById(tunnelId, profileId string) (models.WireguardTunnelInfo, models.WireguardTunnelProfileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelConfigById", tunnelId, profileId)
	ret0, _ := ret[0].(models.WireguardTunnelInfo)
	ret1, _ := ret[1].(models.WireguardTunnelProfileInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTunnelConfigById indicates an expected call of GetTunnelConfigById.
func (mr *MockWireguardTunnelServiceMockRecorder) GetTunnelConfigById(tunnelId, profileId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelConfigById", reflect.TypeOf((*MockWireguardTunnelService)(nil).GetTunnelConfigById), tunnelId, profileId)
}

// GetTunnelInfo mocks base method.
func (m *MockWireguardTunnelService) GetTunnelInfo(tunnelId string) (models.WireguardTunnelInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelInfo", tunnelId)
	ret0, _ := ret[0].(models.WireguardTunnelInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelInfo indicates an expected call of GetTunnelInfo.
func (mr *MockWireguardTunnelServiceMockRecorder) GetTunnelInfo(tunnelId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelInfo", reflect.TypeOf((*MockWireguardTunnelService)(nil).GetTunnelInfo), tunnelId)
}

// GetTunnels mocks base method.
func (m *MockWireguardTunnelService) GetTunnels() map[string]models.WireguardTunnelInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnels")
	ret0, _ := ret[0].(map[string]models.WireguardTunnelInfo)
	return ret0
}

// GetTunnels indicates an expected call of GetTunnels.
func (mr *MockWireguardTunnelServiceMockRecorder) GetTunnels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnels", reflect.TypeOf((*MockWireguardTunnelService)(nil).GetTunnels))
}

// OnBoot mocks base method.
func (m *MockWireguardTunnelService) OnBoot() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnBoot")
	ret0, _ := ret[0].(error)
	return ret0
}

// OnBoot indicates an expected call of OnBoot.
func (mr *MockWireguardTunnelServiceMockRecorder) OnBoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBoot", reflect.TypeOf((*MockWireguardTunnelService)(nil).OnBoot))
}

// RefreshTunnelInterfacesInformation mocks base method.
func (m *MockWireguardTunnelService) RefreshTunnelInterfacesInformation() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTunnelInterfacesInformation")
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshTunnelInterfacesInformation indicates an expected call of RefreshTunnelInterfacesInformation.
func (mr *MockWireguardTunnelServiceMockRecorder) RefreshTunnelInterfacesInformation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTunnelInterfacesInformation", reflect.TypeOf((*MockWireguardTunnelService)(nil).RefreshTunnelInterfacesInformation))
}
